trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        buildContext: $(Build.SourcesDirectory)
        dockerfile: '$(Build.SourcesDirectory)/sample-dotnet-api/Dockerfile'
        repository: salilponde/sample-dotnet-api
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push image to Docker Hub
      inputs:
        containerRegistry: 'Docker Hub'
        repository: salilponde/sample-dotnet-api
        command: 'push'
        tags: |
          $(tag)
